exports.user = {
    "id":null,    
    "uid":null,
    "fullName":null,
    "phoneNumber":null,    
    "email":null,
    "password":null,
    "dateCreated":null,
    "lastUpdate":null,
    "donations":null,
    "requests":null,
    "lastSeen":null,
    "accountType":null,
    "verified":null,
    "status":null,
    "token":null,
    "deviceDetail":null,
    "profilePhotoUrl":null
} 